[package]
name = "logd-logger"
version = "0.1.0"
authors = ["Felix Obenhuber <felix.obenhuber@esrlabs.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/flxo/logd-logger"
homepage = "https://github.com/flxo/logd_logger"
keywords = [
    "adb",
    "android",
    "log",
    "logcat",
    "logger",
]

[dependencies]
env_logger = { version = "0.7.1", features = ["regex"], default-features = false }
log = { version = "0.4.11", features = ["std"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
chrono = "0.4.13"

[target.'cfg(target_os = "android")'.dependencies]
crossbeam = "0.7.3"
bytes = "0.5.6"

[target.'cfg(unix)'.dependencies]
libc = "0.2.73"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi"] }

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1.57"
